# This AWS Lambda function takes a base64-encoded image, 
# uses Amazon Rekognition to detect labels, 
# and maps those labels to predefined categories. 
# It returns a list of relevant categories if the detected labels have a confidence level greater than 75%.

import json
import base64
import boto3

def lambda_handler(event, context):
    label_to_category = {
"Mobile Phone": ["Mobile Phones & Accessories"],
"Cell Phone": ["Mobile Phones & Accessories"],
"Adapter": ["Mobile Phones & Accessories", "Computers & Computer Parts", "Laptops & Tablets"],
"Device": ["Mobile Phones & Accessories", "Laptops & Tablets", "Computers & Computer Parts"],
"Tripod": ["Mobile Phones & Accessories", "Cameras"],
"Plug": ["Mobile Phones & Accessories"],
"iPhone": ["Mobile Phones & Accessories"],



"TV": ["TV"],
"Television": ["TV"],
"Remote Control": ["TV"],


"Fitness": ["Sports Wear for Women", "Sports Wear for Men"],
"Fencing": ["Sports Wear for Women", "Sports Wear for Men"],
"Figure Skating": ["Sports Wear for Women", "Sports Wear for Men"],
"Yoga": ["Sports Wear for Women", "Sports Wear for Men"],
"Working Out": ["Sports Wear for Women", "Sports Wear for Men"],
"Wrestling": ["Sports Wear for Women", "Sports Wear for Men"],
"Swimming Cap": ["Sports Wear for Women", "Sports Wear for Men"],
"Swimming Trunks": ["Sports Wear for Women", "Sports Wear for Men"],
"Spandex": ["Sports Wear for Women", "Sports Wear for Men", "Clothing for Women", "Clothing for Men"],
"Jersey": ["Sports Wear for Women", "Sports Wear for Men"],
"Football Helmet": ["Sports Wear for Women", "Sports Wear for Men"],



"Accessories": ["Accessories for Women", "Accessories for Men"],
"Accessory": ["Accessories for Women", "Accessories for Men"],
"Beanie": ["Accessories for Women", "Accessories for Men"],
"Baseball Cap": ["Accessories for Women", "Accessories for Men"],
"Cap": ["Accessories for Women", "Accessories for Men"],
"Glasses": ["Accessories for Women", "Accessories for Men"],
"Glove": ["Accessories for Women", "Accessories for Men"],
"Sunglasses": ["Accessories for Women", "Accessories for Men"],
"Cowboy Hat": ["Accessories for Women", "Accessories for Men"],
"Wallet": ["Accessories for Women", "Accessories for Men"],
"Tote Bag": ["Accessories for Women", "Accessories for Men"],
"Sombrero": ["Accessories for Women", "Accessories for Men"],
"Sun Hat": ["Accessories for Women", "Accessories for Men"],
"Suspenders": ["Accessories for Women", "Accessories for Men"],
"Scarf": ["Accessories for Women", "Accessories for Men"],
"Necktie": ["Accessories for Women", "Accessories for Men"],
"Sash": ["Accessories for Women", "Accessories for Men"],
"Mask": ["Accessories for Women", "Accessories for Men"],
"Locket": ["Accessories for Women", "Accessories for Men"],
"Hat": ["Accessories for Women", "Accessories for Men"],
"Hair Slide": ["Accessories for Women", "Accessories for Men"],
"Headband": ["Accessories for Women", "Accessories for Men"],


"Jeans": ["Clothing for Women", "Clothing for Men"],
"Denim": ["Clothing for Women", "Clothing for Men"],
"Clothing": ["Clothing for Women", "Clothing for Men"],
"Apparel": ["Clothing for Women", "Clothing for Men"],
"Knitwear": ["Clothing for Women", "Clothing for Men"],
"Knitted Clothes": ["Clothing for Women", "Clothing for Men"],
"Beachwear": ["Clothing for Women", "Clothing for Men"],
"Blazer": ["Clothing for Women", "Clothing for Men"],
"Coat": ["Clothing for Women", "Clothing for Men"],
"Hoodie": ["Clothing for Women", "Clothing for Men"],
"Jacket": ["Clothing for Women", "Clothing for Men"],
"Overcoat": ["Clothing for Women", "Clothing for Men"],
"Pants": ["Clothing for Women", "Clothing for Men"],
"Shorts": ["Clothing for Women", "Clothing for Men"],
"Sock": ["Clothing for Women", "Clothing for Men"],
"Swimming Trunks": ["Clothing for Women", "Clothing for Men"],
"Swimwear": ["Clothing for Women", "Clothing for Men"],
"T-shirt": ["Clothing for Women", "Clothing for Men"],
"Vest": ["Clothing for Women", "Clothing for Men"],
"Dress Shirt": ["Clothing for Women", "Clothing for Men"],
"Fleece": ["Clothing for Women", "Clothing for Men"],
"Undershirt": ["Clothing for Women", "Clothing for Men"],
"Underwear": ["Clothing for Women", "Clothing for Men"],
"Sweater": ["Clothing for Women", "Clothing for Men"],
"Sweatshirt": ["Clothing for Women", "Clothing for Men"],
"Tank Top": ["Clothing for Women", "Clothing for Men"],
"Tie": ["Clothing for Women", "Clothing for Men"],
"Stocking": ["Clothing for Women", "Clothing for Men"],
"Stole": ["Clothing for Women", "Clothing for Men"],
"Suit": ["Clothing for Women", "Clothing for Men"],
"Suspenders": ["Clothing for Women", "Clothing for Men"],
"Skirt": ["Clothing for Women", "Clothing for Men"],
"Sleeve": ["Clothing for Women", "Clothing for Men"],
"Polo": ["Clothing for Women", "Clothing for Men"],
"Robe": ["Clothing for Women", "Clothing for Men"],
"Cardigan": ["Clothing for Women", "Clothing for Men"],
"Sailor Suit": ["Clothing for Women", "Clothing for Men"],
"Sari": ["Clothing for Women", "Clothing for Men"],
"Shirt": ["Clothing for Women", "Clothing for Men"],
"Pajamas": ["Clothing for Women", "Clothing for Men"],
"Military Uniform": ["Clothing for Women", "Clothing for Men"],
"Jersey": ["Clothing for Women", "Clothing for Men"],
"Kilt": ["Clothing for Women", "Clothing for Men"],
"Khaki": ["Clothing for Women", "Clothing for Men"],
"Kimono": ["Clothing for Women", "Clothing for Men"],
"Latex Clothing": ["Clothing for Women", "Clothing for Men"],
"Leather Jacket": ["Clothing for Women", "Clothing for Men"],
"Formal Wear": ["Clothing for Women", "Clothing for Men"],


"Poster": ["Stationery"],
"Flyer": ["Stationery"],
"Drawing": ["Stationery"],
"Sketch": ["Stationery"],
"Illustrated": ["Stationery"],
"Banner": ["Stationery"],
"Business Card": ["Stationery"],
"Calculator": ["Stationery"],
"Document": ["Stationery"],
"Pen": ["Stationery"],
"Notebook": ["Stationery"],
"Scissors": ["Stationery"],
"White Board": ["Stationery"],
"Crayon": ["Stationery"],
"Diary": ["Stationery"],
"File": ["Stationery"],
"File Binder": ["Stationery"],
"File Folder": ["Stationery"],
"Envelope": ["Stationery"],
"Technical Drawing": ["Stationery"],
"Sticker": ["Stationery"],
"Stencil": ["Stationery"],
"Rubber Eraser": ["Stationery"],
"Pencil": ["Stationery"],
"Pencil Box": ["Stationery"],
"Pin": ["Stationery"],
"Map": ["Stationery"],
"Marker": ["Stationery"],
"Letter": ["Stationery"],
"Letter Opener": ["Stationery"],
"Greeting Card": ["Stationery"],
"Fountain Pen": ["Stationery"],

"Chime": ["Home Decor & Appliances"],
"Windchime": ["Home Decor & Appliances"],
"Heater": ["Home Decor & Appliances"],
"Patio Umbrella": ["Home Decor & Appliances"],
"Garden Umbrella": ["Home Decor & Appliances"],
"Hot Tub": ["Home Decor & Appliances"],
"Jacuzzi": ["Home Decor & Appliances"],
"Clothes Iron": ["Home Decor & Appliances"],
"Iron": ["Home Decor & Appliances"],
"Washer": ["Home Decor & Appliances"],
"Dryer": ["Home Decor & Appliances"],
"Alarm Clock": ["Home Decor & Appliances"],
"Analog Clock": ["Home Decor & Appliances"],
"Bath Towel": ["Home Decor & Appliances"],
"Bathtub": ["Home Decor & Appliances"],
"Bathroom": ["Home Decor & Appliances"],
"Bed Sheet": ["Home Decor & Appliances"],
"Blanket": ["Home Decor & Appliances"],
"Blender": ["Home Decor & Appliances"],
"Bowl": ["Home Decor & Appliances"],
"Candle": ["Home Decor & Appliances"],
"Candlestick": ["Home Decor & Appliances"],
"Can opener": ["Home Decor & Appliances"],
"Chair": ["Home Decor & Appliances"],
"Cereal Bowl": ["Home Decor & Appliances"],
"Chest of Drawers": ["Home Decor & Appliances"],
"China Cabinet": ["Home Decor & Appliances"],
"Chopping Board": ["Home Decor & Appliances"],
"Chopsticks": ["Home Decor & Appliances"],
"Christmas Decorations": ["Home Decor & Appliances"],
"Christmas Stocking": ["Home Decor & Appliances"],
"Christmas Tree": ["Home Decor & Appliances"],
"Christmas Tree Ornaments": ["Home Decor & Appliances"],
"Clock": ["Home Decor & Appliances"],
"Photo Frame": ["Home Decor & Appliances"],
"Coat Rack": ["Home Decor & Appliances"],
"Coffee Cup": ["Home Decor & Appliances"],
"Coffee Table": ["Home Decor & Appliances"],
"Coach": ["Home Decor & Appliances"],
"Crib": ["Home Decor & Appliances"],
"Cup": ["Home Decor & Appliances"],
"Desk": ["Home Decor & Appliances"],
"Couch": ["Home Decor & Appliances"],
"Cradle": ["Home Decor & Appliances"],
"Stuffing": ["Home Decor & Appliances"],
"Cork": ["Home Decor & Appliances"],
"Glitter": ["Home Decor & Appliances"],
"Dining Table": ["Home Decor & Appliances"],
"Disposable Cup": ["Home Decor & Appliances"],
"Fork": ["Home Decor & Appliances"],
"Knife": ["Tools & Hardware", "Home Decor & Appliances", "Outdoor & Adventure Gear"],
"Lamp": ["Home Decor & Appliances"],
"Microwave": ["Home Decor & Appliances"],
"Painting": ["Home Decor & Appliances"],
"Plants": ["Home Decor & Appliances"],
"Plate": ["Home Decor & Appliances"],
"Refrigerator": ["Home Decor & Appliances"],
"Rug": ["Home Decor & Appliances"],
"Shower Faucet": ["Home Decor & Appliances"],
"Wine Bottle": ["Home Decor & Appliances"],
"Wine": ["Home Decor & Appliances"],
"Wall Clock": ["Home Decor & Appliances"],
"Soup Bowl": ["Home Decor & Appliances"],
"Spatula": ["Home Decor & Appliances"],
"Sponge": ["Home Decor & Appliances"],
"Spoon": ["Home Decor & Appliances"],
"Statue": ["Home Decor & Appliances"],
"Scale": ["Home Decor & Appliances"],
"Steamer": ["Home Decor & Appliances"],
"Mirror": ["Home Decor & Appliances"],
"Stove": ["Home Decor & Appliances"],
"Straw": ["Home Decor & Appliances"],
"Mixer": ["Home Decor & Appliances"],
"Shower Curtain": ["Home Decor & Appliances"],
"Sideboard": ["Home Decor & Appliances"],
"Sink": ["Home Decor & Appliances"],
"Sink Faucet": ["Home Decor & Appliances"],
"Skillet": ["Home Decor & Appliances"],
"Slow Cooker": ["Home Decor & Appliances"],
"Soap": ["Home Decor & Appliances"],
"Sliding Door": ["Home Decor & Appliances"],
"Solar Panels": ["Home Decor & Appliances"],
"Plant": ["Home Decor & Appliances"],
"Planter": ["Home Decor & Appliances"],
"Plate Rack": ["Home Decor & Appliances"],
"Platter": ["Home Decor & Appliances"],
"Plastic": ["Home Decor & Appliances"],
"Plastic Bag": ["Home Decor & Appliances"],
"Plastic Wrap": ["Home Decor & Appliances"],
"Porcelain": ["Home Decor & Appliances"],
"Pot": ["Home Decor & Appliances"],
"Potted Plant": ["Home Decor & Appliances"],
"Pottery": ["Home Decor & Appliances"],
"Pressure Cooker": ["Home Decor & Appliances"],
"Palette": ["Home Decor & Appliances"],
"Pantry": ["Home Decor & Appliances"],
"Patio": ["Home Decor & Appliances"],
"Pattern": ["Home Decor & Appliances"],
"Pillow": ["Home Decor & Appliances"],
"Lampshade": ["Home Decor & Appliances"],
"Globe": ["Home Decor & Appliances"],
"Home Decor": ["Home Decor & Appliances"],


"Handsaw": ["Tools & Hardware"],
"Hacksaw": ["Tools & Hardware"],
"Bucket": ["Tools & Hardware"],
"Chain Saw": ["Tools & Hardware"],
"Lawn Mower": ["Tools & Hardware"],
"Power Drill": ["Tools & Hardware"],
"Screwdriver": ["Tools & Hardware"],
"Shovel": ["Tools & Hardware"],
"Flashlight": ["Tools & Hardware"],
"Electrical Outlet": ["Tools & Hardware"],
"Engine": ["Tools & Hardware"],
"Welding": ["Tools & Hardware"],
"Wheel": ["Tools & Hardware"],
"Wheelbarrow": ["Tools & Hardware"],
"Wrench": ["Tools & Hardware"],
"Wire": ["Tools & Hardware"],
"Woodworking": ["Tools & Hardware"],
"Workshop": ["Tools & Hardware"],
"Spray Can": ["Tools & Hardware"],
"Stencil": ["Tools & Hardware"],
"Steel": ["Tools & Hardware"],
"Snowplow": ["Tools & Hardware"],
"Rake": ["Tools & Hardware"],
"Screw": ["Tools & Hardware"],
"Pipeline": ["Tools & Hardware"],
"Pliers": ["Tools & Hardware"],
"Plumbing": ["Tools & Hardware"],
"Plywood": ["Tools & Hardware"],
"Pump": ["Tools & Hardware"],
"Nail": ["Tools & Hardware"],
"Paint Container": ["Tools & Hardware"],
"Mallet": ["Tools & Hardware"],
"Mattock": ["Tools & Hardware"],
"Gear": ["Tools & Hardware"],
"Handle": ["Tools & Hardware"],
"Hoe": ["Tools & Hardware"],



"Monitor": ["Computers & Computer Parts", "Laptops & Tablets"],
"Display": ["Computers & Computer Parts", "Laptops & Tablets"],
"Digital Display": ["Computers & Computer Parts", "Laptops & Tablets"],
"LCD Screen": ["Computers & Computer Parts", "Laptops & Tablets"],
"Computer": ["Computers & Computer Parts"],
"Computer Hardware": ["Computers & Computer Parts"],
"Computer Keyboard": ["Computers & Computer Parts"],
"CPU": ["Computers & Computer Parts"],
"Disk": ["Computers & Computer Parts"],
"Desktop": ["Computers & Computer Parts", "Laptops & Tablets"],
"Electronic Chip": ["Computers & Computer Parts"],
"Electronics": ["Computers & Computer Parts"],
"Webcam": ["Computers & Computer Parts"],
"Surface Computer": ["Computers & Computer Parts"],
"RAM Memory": ["Computers & Computer Parts"],
"Screen": ["Computers & Computer Parts"],
"Mouse": ["Computers & Computer Parts"],
"Mousepad": ["Computers & Computer Parts"],
"Keyboard": ["Computers & Computer Parts"],
"Hard Disk": ["Computers & Computer Parts"],
"Hand-Held Computer": ["Computers & Computer Parts"],


"Headphones": ["Sound Systems & Accessories"],
"Headset": ["Sound Systems & Accessories"],
"Speaker": ["Sound Systems & Accessories"],
"Audio Speaker": ["Sound Systems & Accessories"],
"Amplifier": ["Sound Systems & Accessories"],
"Earbuds": ["Sound Systems & Accessories"],
"Microphone": ["Sound Systems & Accessories"],
"Tape Player": ["Sound Systems & Accessories"],
"Stereo": ["Sound Systems & Accessories"],
"Radio": ["Sound Systems & Accessories"],


"Anklet": ["Accessories for Women"],
"Bangles": ["Accessories for Women"],
"Bead Necklace": ["Accessories for Women"],
"Bracelet": ["Accessories for Women"],
"Brooch": ["Accessories for Women"],
"Handbag": ["Accessories for Women"],
"Feather Boa": ["Accessories for Women"],
"Purse": ["Accessories for Women"],
"Veil": ["Accessories for Women"],


"Bow Tie": ["Accessories for Men"],
"Tie": ["Accessories for Men"],


"Blouse": ["Clothing for Women"],
"Bra": ["Clothing for Women"],
"Skirt": ["Clothing for Women"],
"Wedding Gown": ["Clothing for Women"],
"Corset": ["Clothing for Women"],
"Dress": ["Clothing for Women"],
"Evening Dress": ["Clothing for Women"],
"Thong": ["Clothing for Women"],
"Pantyhose": ["Clothing for Women"],
"Miniskirt": ["Clothing for Women"],
"Long Sleeve": ["Clothing for Women"],
"Gown": ["Clothing for Women"],


"Tuxedo": ["Clothing for Men"],
"Turban": ["Clothing for Men"],

"Violin": ["Musical Instruments & Gear"],
"Viola": ["Musical Instruments & Gear"],
"Fiddle": ["Musical Instruments & Gear"],
"Tuba": ["Musical Instruments & Gear"],
"Euphonium": ["Musical Instruments & Gear"],
"Xylophone": ["Musical Instruments & Gear"],
"Vibraphone": ["Musical Instruments & Gear"],
"Glockenspiel": ["Musical Instruments & Gear"],
"Guitarist": ["Musical Instruments & Gear"],
"Playing Guitar": ["Musical Instruments & Gear"],
"Pianist": ["Musical Instruments & Gear"],
"Playing Piano": ["Musical Instruments & Gear"],
"Accordion": ["Musical Instruments & Gear"],
"Banjo": ["Musical Instruments & Gear"],
"Bass Guitar": ["Musical Instruments & Gear"],
"Bongo": ["Musical Instruments & Gear"],
"Clarinet": ["Musical Instruments & Gear"],
"Guitar": ["Musical Instruments & Gear"],
"Piano": ["Musical Instruments & Gear"],
"Conga": ["Musical Instruments & Gear"],
"Cowbell": ["Musical Instruments & Gear"],
"Drum": ["Musical Instruments & Gear"],
"Drummer": ["Musical Instruments & Gear"],
"Electric Guitar": ["Musical Instruments & Gear"],
"Trombone": ["Musical Instruments & Gear"],
"Trumpet": ["Musical Instruments & Gear"],
"Upright Piano": ["Musical Instruments & Gear"],
"Whistle": ["Musical Instruments & Gear"],
"Saxophone": ["Musical Instruments & Gear"],
"Musical Instrument": ["Musical Instruments & Gear"],
"Oboe": ["Musical Instruments & Gear"],
"Harmonica": ["Musical Instruments & Gear"],
"Harp": ["Musical Instruments & Gear"],
"Gong": ["Musical Instruments & Gear"],
"Flugelhorn": ["Musical Instruments & Gear"],
"Flute": ["Musical Instruments & Gear"],
"French Horn": ["Musical Instruments & Gear"],

"Baseball": ["Sports Equipment"],
"Softball": ["Sports Equipment"],
"Ping Pong": ["Sports Equipment"],
"Table Tennis": ["Sports Equipment"],
"Cycling": ["Sports Equipment"],
"Cyclist": ["Sports Equipment"],
"Bike Cyclist": ["Sports Equipment"],
"Baseball (ball)": ["Sports Equipment"],
"Baseball Bat": ["Sports Equipment"],
"Basketball (Ball)": ["Sports Equipment"],
"Baton": ["Sports Equipment"],
"Battling Ropes": ["Sports Equipment"],
"Bicycle": ["Sports Equipment"],
"Bowling Ball": ["Sports Equipment"],
"Bmx": ["Sports Equipment"],
"Cricket Ball": ["Sports Equipment"],
"Cricket Bat": ["Sports Equipment"],
"Ice Hockey Stick": ["Sports Equipment"],
"Kayak": ["Sports Equipment"],
"Ping Pong Paddle": ["Sports Equipment"],
"Scoreboard": ["Sports Equipment"],
"Skateboard": ["Sports Equipment"],
"Volleyball (Ball)": ["Sports Equipment"],
"Darts": ["Sports Equipment"],
"Field Hockey Stick": ["Sports Equipment"],
"Exercise Bike": ["Sports Equipment"],
"Elliptical Trainer": ["Sports Equipment"],
"Water Polo": ["Sports Equipment"],
"Water Skiing": ["Sports Equipment"],
"Swimming Pool": ["Sports Equipment"],
"Tennis": ["Sports Equipment"],
"Tennis Ball": ["Sports Equipment"],
"Tennis Racket": ["Sports Equipment"],
"Tandem Bicycle": ["Sports Equipment"],
"Treadmill": ["Sports Equipment"],
"Surfboard": ["Sports Equipment"],
"Surfing": ["Sports Equipment"],
"Skipping Rope": ["Sports Equipment"],
"Golf Ball": ["Sports Equipment"],
"Golf Cart": ["Sports Equipment"],
"Golf Club": ["Sports Equipment"],
"Gym Weights": ["Sports Equipment"],
"Handball": ["Sports Equipment"],
"Ski Boot": ["Sports Equipment", "Shoes"],
"Skiing": ["Sports Equipment"],
"Snowboarding": ["Sports Equipment"],
"Snowmobile": ["Sports Equipment"],
"Soccer Ball": ["Sports Equipment"],
"Roller Skating": ["Sports Equipment"],
"Rugby Ball": ["Sports Equipment"],
"Riding Bicycle": ["Sports Equipment"],
"Oars": ["Sports Equipment"],
"Paddle": ["Sports Equipment"],
"Parachute": ["Sports Equipment"],
"Motor Scooter": ["Sports Equipment"],
"Mountain Bike": ["Sports Equipment"],
"Ice Hockey Puck": ["Sports Equipment"],
"Kayaking": ["Sports Equipment"],
"Frisbee": ["Sports Equipment"],

"Lipstick": ["Makeup & Cosmetics"],
"Cosmetics": ["Makeup & Cosmetics"],
"Cream": ["Makeup & Cosmetics"],
"Face Makeup": ["Makeup & Cosmetics"],
"Sunscreen": ["Makeup & Cosmetics"],
"Nail Polish": ["Makeup & Cosmetics"],
"Mascara": ["Makeup & Cosmetics"],
"Manicure": ["Makeup & Cosmetics"],
"Makeup": ["Makeup & Cosmetics"],
"Lotion": ["Makeup & Cosmetics"],
"Henna": ["Makeup & Cosmetics"],



"Bookcase": ["Books & Accessories"],
"Bookshelf": ["Books & Accessories"],
"Anime": ["Books & Accessories"],
"Book": ["Books & Accessories"],
"Notebook": ["Books & Accessories"],
"Novel": ["Books & Accessories"],
"Page": ["Books & Accessories"],
"Paper": ["Books & Accessories"],
"Magazine": ["Books & Accessories"],
"Manga": ["Books & Accessories"],


"Laptop": ["Laptops & Tablets"],
"Tablet Computer": ["Laptops & Tablets"],
"Device": ["Laptops & Tablets"],


"Blow Dryer": ["Beauty & Personal Care"],
"Hair Dryer": ["Beauty & Personal Care"],
"Aftershave": ["Beauty & Personal Care"],
"Brush": ["Beauty & Personal Care"],
"Comb": ["Beauty & Personal Care"],
"Perfume": ["Beauty & Personal Care"],
"Razor": ["Beauty & Personal Care"],
"Toothbrush": ["Beauty & Personal Care"],
"Deodorant": ["Beauty & Personal Care"],
"Shampoo": ["Beauty & Personal Care"],

"Bangles": ["Jewelry"],
"Bead Necklace": ["Jewelry"],
"Bracelet": ["Jewelry"],
"Brooch": ["Jewelry"],
"Locket": ["Jewelry"],
"Necklace": ["Jewelry"],
"Crown": ["Jewelry"],
"Crucifix": ["Jewelry"],
"Crystal": ["Jewelry"],
"Diamond": ["Jewelry"],
"Earring": ["Jewelry"],
"Emblem": ["Jewelry"],
"Emerald": ["Jewelry"],
"Tiara": ["Jewelry"],
"Silver": ["Jewelry"],
"Ring": ["Jewelry"],
"Sapphire": ["Jewelry"],
"Pendant": ["Jewelry"],
"Opal": ["Jewelry"],
"Pearl": ["Jewelry"],
"Gold": ["Jewelry"],
"Gemstone": ["Jewelry"],


"Camera": ["Cameras"],
"Camera Lens": ["Cameras"],
"Digital Camera": ["Cameras"],
"Fisheye": ["Cameras"],
"Video Camera": ["Cameras"],
"Webcam": ["Cameras"],
"Portrait": ["Cameras"],
"Lens Cap": ["Cameras"],


"High Heel": ["Shoes"],
"Sandal": ["Shoes"],
"Shoe": ["Shoes"],
"Cowboy Boot": ["Shoes"],
"Flip-Flop": ["Shoes"],
"Wedge": ["Shoes"],
"Sneaker": ["Shoes"],
"Riding Boot": ["Shoes"],
"Running Shoe": ["Shoes"],
"Footwear": ["Shoes"],
"Boot": ["Shoes"],

"VR Headset": ["Gaming Consoles & Video Games"],

"Wristwatch": ["Watches"],
"Digital Watch": ["Watches"],
"Stopwatch": ["Watches"],


"Concert": ["Music & Movies"],
"Dvd": ["Music & Movies"],
"iPod": ["Music & Movies"],


"Suitcase": ["Travel Accessories"],

"Slingshot": ["Outdoor & Adventure Gear"],
"Helmet": ["Outdoor & Adventure Gear"],
"Lifejacket": ["Outdoor & Adventure Gear"],
"Fishing Lure": ["Outdoor & Adventure Gear"],
"Binoculars": ["Outdoor & Adventure Gear"],
"Crossbow": ["Outdoor & Adventure Gear"],
"Hook": ["Outdoor & Adventure Gear"],




    }

    rekognition = boto3.client('rekognition', region_name='us-east-1')
    
    try:
        if 'body' in event:
            request_body = json.loads(event['body'])
            image_bytes = base64.b64decode(request_body['image'])

            response = rekognition.detect_labels(Image={'Bytes': image_bytes}, MaxLabels=10)
            print("Rekognition Response:", response)

            categories = {}
            
            for label in response.get('Labels', []):
                print(f"Label: {label['Name']}, Confidence: {label['Confidence']}")
                if label['Confidence'] > 75:
                    label_name = label['Name']
                    if label_name in label_to_category:
                        assigned_categories = label_to_category[label_name]
                        print(f"Assigned Categories for {label_name}: {assigned_categories}")
                        for category in assigned_categories:
                            categories[category] = True  # Use a dictionary with category names as keys
            
            # Convert the dictionary keys to a list to return only the category names
            category_list = list(categories.keys())
            print("Final Categories:", category_list)

            return {
                'statusCode': 200,
                'body': json.dumps(category_list),
                'headers': {'Content-Type': 'application/json'}
            }
    except Exception as e:
        return {
            'statusCode': 500,
            'body': json.dumps({'error': str(e)}),
            'headers': {'Content-Type': 'application/json'}
        }
